### ISSUE TITLE
Register a new account - UI

### ISSUE THREAD

**Issue by jijo125-github** [jijo125-github/Authentication-App#1]
- A new user should be able to register (UI)
- Deny registration if already registered (UI)

**Comment by jijo125-github** [comment]
- A new user should be able to register successfully. 
- Deny registration if already registered.

**Comment by jijo125-github** [comment]
Story Points - 3

**Comment by yashchavda57** [comment]
Added UI using angular for registering new user.
Added functionality where user can 
1. Register using email id
2. Register using Google account authentication

**Comment by jijo125-github** [comment]
Able to login using Social Services such as Google / Facebook.
